spring.application.name=debt-settlement
server.forward-headers-strategy=framework

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/fairshare_db
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# --- Spring Security & OAuth2 Configuration ---
# You will get these keys from the Google Cloud Console later
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:your-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:your-client-secret}
spring.security.oauth2.client.registration.google.scope=profile, email

# --- JWT Configuration ---
# This is a 256-bit secret key used to digitally sign our VIP wristbands.
jwt.secret=${JWT_SECRET:c3VwZXItc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmchIQ==}
jwt.expiration=86400000
# Expiration is in milliseconds (86400000 ms = 1 full day)

app.frontend.redirect-uri=${FRONTEND_REDIRECT_URI:exp://localhost:8081/--/login-success}